### ISSUE TITLE
clean filter list view

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#415]
Hi,

I'd like to suggest a small change on filter. Just add a button for remove all filters buttom.

When the user selected many filters, he needs to remove one by one.

This button just call the same URL removing all query_string formed by the specified filters.

By.
![filter1](https://f.cloud.github.com/assets/5805339/1641616/ce8fd0b0-585b-11e3-90e6-501822e9356d.jpg)
![filter2](https://f.cloud.github.com/assets/5805339/1641617/d1c04896-585b-11e3-8eff-a39e3261321d.jpg)

**Comment by iamanoopmk** [comment]
Most of my apps invariably use multiple filters. So, waiting for each filter to reload the page is cumbersome. Django REST Framework's filter option is a good example where it allows inputting multiple filters at once and then fetching the results. That would be more user-friendly since I would not mind pressing an extra button to load results.

**Comment by sehmaschine** [comment]
Closing this for now since the ticket is very old. Besides, I think it is already solved with using the changelist_filter_confirm template. If there's something else we should fix with regards to this issue, please open a new ticket.
