### ISSUE TITLE
Allow to search for related fields in autocomplete_search_fields

### ISSUE THREAD

**Issue by olivierdalang** [sehmaschine/django-grappelli#671]
Hi!
Would it be possible to add related field in autocomplete_search_fields? 
Example:
```
@staticmethod
    def autocomplete_search_fields():
        return ("artist__name__icontains",)
```
to search for a track using it's artist name. 
This type of searches are supported in the admin search_fields, so it would be consistent. 

By the way, wouldn't it make more sense to define the autocomplete fields in the admin rather than in the model? That would allow to have different fields searched on different admin models. 

Thanks for grappelli, it's awesome!

**Comment by sehmaschine** [comment]
a) searching related fields should be possible
b) comparing the autocomplete search with the change-list admin search is misleading. these options are not related whatsoever.
c) defining the autocomplete fields within admin (rather than the model) would be nice. unfortunately, I don't think that's possible. but if someone comes up with a good idea on how to implement that, I'm all ears.

besides, please use the google-group for asking questions ... thank you!
