### ISSUE TITLE
Simplify Dashboard Design by Removing Redundant Change Link

### ISSUE THREAD

**Issue by jpotterm** [sehmaschine/django-grappelli#672]
I propose removing the "change" link on the dashboard because it is redundant. Clicking on the name of the model will bring you to the change list and that's a much more natural way to get there. Having the change link adds visual clutter and leaves less space for long model names in the smaller (2nd & 3rd) columns.

This is how it currently looks:

![original](https://cloud.githubusercontent.com/assets/134310/10249988/6044cb8a-68f6-11e5-8b6a-55f4ffa93137.png)

Proposal number 1 is simply removing the change link:

![proposal_1](https://cloud.githubusercontent.com/assets/134310/10250003/7d1cf908-68f6-11e5-831d-05064ed023ef.png)

Proposal number 2 is simplifying it even more and just keeping the add icon:

![proposal_2](https://cloud.githubusercontent.com/assets/134310/10250021/8fd33a8a-68f6-11e5-9d8e-63ea7b92dd2b.png)

The added visual complexity of having the unnecessary change link really adds up when you have a large dashboard full of them. Removing them will make it feel much cleaner and easier to use.

I'd be happy to submit a pull request if you would accept it.

**Comment by parsch** [comment]
@jpotterm I like both your proposals (removing the changelink, simplifying the addlink). Before submitting a pr, please make sure that different user permission scenarios are still satisfied.

**Comment by trevoriancox** [comment]
+1 Proposal 2. I don't think there are any permission concerns here.

I like the &#9776; icon that was associated with the Change link, so I have added it to the model name link:

    .grp-dashboard-module .grp-row a {
        /* copied formatting from li.grp-change-link: */
        background: url('../images/icons-small-s7d28d7943b.png') no-repeat;
        background-position: 0 -3753px;
        padding-left: 18px;
    }

This change and others are in my fork:  

> https://github.com/trevoriancox/django-grappelli
  Increase all text sizes 1-2px and use bold links.
  Make all dashboard links same size text.
  Dashboard header using link colour instead of white.
  Remove "Change", "Add" text from dashboard model list for cleaner design.
  Show grp-change-link's hamburger icon next to model name link on dashboard.
  Change media="screen" to media="all" to support printing.
