### ISSUE TITLE
Grappelli checkboxes don't appear to work

### ISSUE THREAD

**Issue by chasepilon** [sehmaschine/django-grappelli#727]
Django 1.7.6
django-grappelli 2.6.5

With no additional customizations, I have found the select all checkbox is not selecting all items in a list.

This appears to also be impacting list actions such as delete lines

<img width="108" alt="screen shot 2016-02-10 at 9 45 20 am" src="https://cloud.githubusercontent.com/assets/16057931/12950420/17fb88c2-cfdb-11e5-8795-95147e076527.png">

**Comment by parsch** [comment]
Works with my comparable setup (and there have been no reports concerning such a misbehaviour). Did you check if the scripts are loaded correctly?

**Comment by chasepilon** [comment]
Steps:
* pip install django-grappelli==2.6.5
* added 'grappelli' to INSTALLED_APPS in settings.py before django.contrib.admin
* added url(r'^grappelli/', include('grappelli.urls')), to urls.py under urlpatterns
* removed my admin template folder
* ran python manage.py collectstatic

Beyond that, how would I confirm the scripts loaded properly?

**Comment by sehmaschine** [comment]
@chasepilon you should check if the right grappelli scripts are being loaded (and not the original scripts from the django admin interface), e.g. with using developer tools. I'm closing this for now since it's most probably a setup issue and not a grappelli bug. Please reopen with additional information if you still think this is a bug.
