### ISSUE TITLE
Django 1.9 - Style changes

### ISSUE THREAD

**Issue by cristianocca** [sehmaschine/django-grappelli#731]
Hello,

Is it possible to easily switch to the new styles django added at 1.9 ? It seems that since grappelli renames most of the CSS classes it can't be done easily. Are there any plans to do so?

**Comment by parsch** [comment]
Well, it's easy if you don't use Grappelli but the original Django 1.9. styles if you like them.

**Comment by cristianocca** [comment]
Sorry, do you mean to not use Grappelli at all? Grappelli adds some interesting features like auto complete and more, so it is still required, but I'm not sure how to skip its styles to just get the extra functionallity which is quite useful.






De: parsch
Enviado el: ‎jueves‎, ‎25‎ de ‎febrero‎ de ‎2016 ‎4‎:‎50
Para: sehmaschine/django-grappelli
CC: Cristiano Coelho





Well, it's easy if you don't use Grappelli but the original Django 1.9. styles if you like them.

**Comment by parsch** [comment]
Using Grappelli's functionality without it's styles is not possible.

**Comment by 9gix** [comment]
I believe those functionalities aren't provided by django admin natively. So, perhaps, it is time to decouple those functionalities out from grappelli core such as `autocomplete_lookup_field`, `related_lookup_fields`. So that grappelli only focuses on skin for the Django admin interface without extra functionality.
