### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 15084

### ISSUE THREAD

**Issue by rohitjain-rj** [sehmaschine/django-grappelli#755]
I'm getting this error whenever I open any Django admin add form. This happens only when I try to use grappelli. Without that, the add form opens fine. I'm using postgres database, and I've checked the encoding is UTF8. Is there some config issue?

**Comment by sehmaschine** [comment]
how can we reproduce this?

**Comment by rohitjain-rj** [comment]
I followed the grappelli quick start guide: http://django-grappelli.readthedocs.io/en/latest/quickstart.html to setup.

1. pip install django-grappelli
2. Added 'grappelli' to INSTALLED_APPS, at the top.
3. Added url - 'grappelli/' on urls.py

Then I go to my django admin site, select any model from there. From the Model List page, select any model to visit Update Form, or Click on Add model to visit Add Form. The above error occurs. This happens for all models.

If I remove `grappelli` from INSTALLED_APPS and the url, the form opens fine.

**Comment by sehmaschine** [comment]
I'm not able to reproduce this. Still possible that there's an issue ... but without any further details, we are not able to check this. Since it happens for all models, I'd say it's probably a setup issue (unrelated to grappelli).

Please reopen with detailed instructions on how to reproduce this error – since you get it, it should be much easier for you to debug and give us some hints.

**Comment by rohitjain-rj** [comment]
Ok, just figured out that DEFAULT_CHARSET is set to ISO-8859-1 in my settings file. Strange that it didn't fail with default admin template. May be probably because grappelli uses some other text representation for static text?

**Comment by sehmaschine** [comment]
thanks for the info.
