### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by timkofu** [sehmaschine/django-grappelli#777]
What's the ETA on this?

**Comment by sehmaschine** [comment]
No ETA yet. We hope to start working on 1.10 support soon.

**Comment by timkofu** [comment]
Alright, we shall wait. Thank you for the great work.

**Comment by rcooke** [comment]
I have been testing Django 1.10 with Grappelli for a week without problems.  I just pushed the update to the production server this weekend, and everything seems to be working.  Is there something specific inside Grappelli that needs updating for Django 1.10?

**Comment by sehmaschine** [comment]
ETA is set to September 27th. I assume there are some minor updates needed (esp. in order to remove depreciation warnings, but I'll have a closer look asap).

**Comment by unaizalakain** [comment]
Related: https://github.com/sehmaschine/django-grappelli/pull/779

**Comment by tdruez** [comment]
I've been running Django 1.10 and Grappelli 2.8.1 for a month and everything works fine except for the inline JavaScript @ https://github.com/sehmaschine/django-grappelli/issues/770

Thanks for the great work!

**Comment by rcooke** [comment]
Ah, my users pointed out to me that Dj1.10 Admin tabular inline has some enhancements that are missing from the current Grappelli version.

I'm comparing the two versions to see if I can convert the Django version into a new Grappelli compatible template.  But its going very slow for me since I don't know any of the history behind the Grappelli changes!  I think I'll put this on hold and wait for your update....

**Comment by sehmaschine** [comment]
solved with stable/2.9.x

**Comment by timkofu** [comment]
Been using stable/2.9.x in production for a couple of weeks now; works perfect with 1.10 so far.
