### ISSUE TITLE
unable to change integer field widget from type "text" to "number"

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#798]
Is there something in Grappelli that would override all my attempts to get form widgets for integer fields back to type "number"?

I first tried turning OFF **USE_I18N** and **USE_L10N**.  Then I tried adding jquery to the admin media:

`    django.jQuery(document).ready(function($){`
`      $("[id$=-count]").css("text-align", "center");`
`      $("[id$=-count]").css("width", "4em");`
`      $("[id$=-count]").prop("type", "number");`
`      $("#id_form-0-count").attr("value", "666");`
`    });`

The selector works, I can see the CENTER and width adjustments working.  But not the TYPE change.  I even tried changing the value of one field just to convince myself the **prop** and **attr** functions work.

I'm starting to get annoyed with this and am posting here just in case this is a know and expected thing.

Thanks in advance!

**Comment by sehmaschine** [comment]
we decided to not implement the number field since it behaves (very) different depending on the browser (one browser even accepts en empty field although that field is required, though I don´t remember which browser that was). I also added a django-ticket when we worked on that issue, but I'm currently not able to find that ticket anymore. However, the django devs agreed that the number field behaves badly (although they decided to stick with their solution).

**Comment by rcooke** [comment]
I'll take that as a "No" then?

I implemented a work-around.  I subclassed the Number widget as "MyNumberWidget" and used the Admin widget override to replace the default.  Thankfully that seems to work, now my number fields have the up/down arrows for changing values.

Having those is a requirements for this app.  And of course I said "no problem, a near zero effort change".....  Argh.

I can post the code snippet here in case somebody might need it one day.
