### ISSUE TITLE
Support Django 2.2

### ISSUE THREAD

**Issue by atodorov** [sehmaschine/django-grappelli#891]
Only the top table is somewhat nice and styled, the rest until the bottom of the screen are just a bunch of HTML links squashed together, see screenshot.

I can provide a PR but I'm not exactly sure where to start.

![grapelli_django2 2](https://user-images.githubusercontent.com/1002300/56765033-ce9ee100-67ae-11e9-8c66-98e37528a008.png)

**Comment by sehmaschine** [comment]
I'm not saying that there are no issues with Django 2.2 (actually, Grappelli is not yet compatible with 2.2), but I just tried it and it looks good overall. I guess that your issue is not related to that compatibility.

Your screenshot looks like you've been overwriting some templates. Please try again with a fresh install or remove any customizations. Thanks.

**Comment by ksze** [comment]
@sehmaschine Maybe mark django-grappelli 2.12 to require Django 2.1 using setuptools' [`install_requires` keyword](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires)?

**Comment by atodorov** [comment]
Please don't do this. We use grapelli + Django 2.2.1 and although there may be a few issues it works generally fine. You can add docs or warnings about supported Django versions but make it possible to still use a non-supported one.

**Comment by sehmaschine** [comment]
I agree with @atodorov. Besides, we currently work on compatibility with 2.2. It's only minor issues but we'll update jQuery to 3.3 and this involves some refactoring of the js code.
