### ISSUE TITLE
admin filter issue

### ISSUE THREAD

**Issue by jht001** [sehmaschine/django-grappelli#918]
I tried the latest code with Django 2.2
I had a problem with admin filters with an apply button.
If there is a filter on a custom defined class for a non model field, e.g.

    class DID_LERG_State(admin.SimpleListFilter):
    ...
    list_filter = (DID_LERG_State,)

then admin filters using this class do not work correctly.
I think part of the problem is in **grappelli.js** with this line:

    var filterQueryParams = values && values.filter(el => el.includes(fieldName + '__'));

The model fields have a fieldName with a suffix of "__exact", but custom defined search filters like the one above do not.  This causes an empty filterQueryParams, and the filter is not applied.

In addition in the template file: **templatetags/grp_tags.py**
The line:

    'field_name': spec.field.name,

fails because there is no "field" defined in custom defined filter classes like the one above.

**Comment by sehmaschine** [comment]
@jht001 are you able to send a PR?

**Comment by jht001** [comment]
Sorry, I don't don't have a PR, wasn't sure how to best fix the issues.

**Comment by tdruez** [comment]
This issue was introduce in https://github.com/sehmaschine/django-grappelli/commit/450ae71b9155b4a1d4ce68231cdc42cef922f975#diff-0f54497922dfd94c5b33ba144b5cdcd9

It makes the 2.13.2 release unusable on my side as well.
As @jht001 mentioned, custom admin filter may not have a `field` attribute defined, raising a AttributeError exception at https://github.com/sehmaschine/django-grappelli/commit/450ae71b9155b4a1d4ce68231cdc42cef922f975#diff-0f54497922dfd94c5b33ba144b5cdcd9R220

@parsch I would suggested to replace `'field_name': spec.field.name,` with something like `'field': getattr(spec, 'field'),`  and update the HTML template and JS accordingly.
Let me know what you think about that approach.

**Comment by sehmaschine** [comment]
@jht001 @tdruez we have commited a fix. would be great if you can check it with your setup. it works for us with custom filters. the patch is in stable/2.13.x.

**Comment by tdruez** [comment]
@sehmaschine thanks for the patch!
I've reviewed and tested it in my setup and everything works fine.
Could you publish a new release including the fix?

**Comment by sehmaschine** [comment]
just did a new release.

**Comment by rcooke** [comment]
I have not had time to try this again.  Is this in the pypy release now?  Or do I still need to checkout a specific branch?

**Comment by sehmaschine** [comment]
yes, it is in the release (2.13.4).
