### ISSUE TITLE
Remove Grappelli autocomplete in favour of Django/Select2

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#929]
Since Django now has a useful option for autocompletes with Select2, we could think about removing this Grappelli feature IMO. It would help with cleaning up the codebase and following Django releases is much easier without our custom autocomplete option. The only thing currently missing with Django is autocompletes with Generic fields. Besides, I'd also think about removing the related fields functionality (showing the label beneath the input field) – but that's also something which is missing with Django. If we remove both related/autocomplet options with Grappelli, we definitely lose a couple of features – but future development will be easier. 

Looking forward to hear opinions on that.

**Comment by pasevin** [comment]
It makes sense to drop autocomplete as it's already supported by Django and will probably evolve further. I frequently encounter issues with various plugins conflicting with Django autocomplete since they rolled it out. Imagine it's a pain, to try to override it.

As for the related fields functionality, I haven't used this so I have no opinion.

All in all, I think the best course is to keep having great core features and not overburden yourself with too many. Let other devs create plugins for Grappelli :)

P.S:
And maybe look into updating the skin to support responsiveness or at least mobile screens.

P.P.S Thanks for all your work!

**Comment by bobort** [comment]
I am new to Grappelli and applied it to an admin site that was already using Django admin `autocomplete_fields`. Grappelli interfered with the Django rendering and made them unusable. I had to switch to the Grappelli way of autocompletes. Based on this experience, I found the Django autocompletes to be the superior autocomplete method. I am all for you deprecating autocompletes in Grappelli. If anything, you could style the drop down to match the Grappelli theme better, but I think it's really nice as it already is.

**Comment by sehmaschine** [comment]
see #981
