### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by c0d5x** [sehmaschine/django-grappelli#934]
With jQuery being deprecated, and new security vulnerabilities not patched it is important to migrate to a maintained library/framework.

https://blog.jqueryui.com/2017/12/the-future-of-jquery-ui-and-jquery-mobile/

Which framework/project could Grappelli migrate to that provides more features and better support?
Are there plans to start a feature branch for this?

Thanks

**Comment by sehmaschine** [comment]
You mean jQuery UI, not jQuery ... right?

**Comment by c0d5x** [comment]
No, I mean jQuery, and of course jQuery UI.
jQuery is pointless for the most part, and it is also a matter of how far behind will grappelli be by keeping deprecated dependencies.

https://www.reddit.com/r/webdev/comments/biyzg1/is_jquery_dead/

**Comment by sehmaschine** [comment]
As long as Djano relies on jQuery, we will do that as well (because we use parts of the Django JS implementation).

Besides, I don't fully agree with jQuery being deprecated. We've been using React for all our projects for quite some time now ... but React is a totally different beast and IMO you cannot compare it with jQuery.

Best case: Django delivers an API for the admin interface. Grappelli is a pure skin (done with React or Vue,).

I'm closing this for now, because I don't see any short-term solution. If Django removes the admin interface and provides an API instead, it's a different story.
