### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [sehmaschine/django-grappelli#943]
Wheels (`.whl`) for this package are currently missing from PyPI. Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by atodorov** [comment]
@sehmaschine what about a build & upload script or something similar so that both tarballs and wheels are built & uploaded together ? In a number of packages I maintain I use variations of this https://github.com/kiwitcms/Kiwi/blob/master/tests/check-build.  For example https://github.com/PyCQA/pylint-django/blob/master/scripts/build.sh

**Comment by sehmaschine** [comment]
uploaded for current version (2.14.2) and implemented for future versions as well.
