### ISSUE TITLE
`change_list_filter_confirm` is using `admin_list.admin_list_filter` instead of `grp_tags.admin_list_filter`

### ISSUE THREAD

**Issue by pricco** [sehmaschine/django-grappelli#967]
Packages:
Django==3.2.2
django-grappelli==2.15.1

The current `change_list_filter_confirm` contains:
`{% load i18n grp_tags admin_urls static admin_list %}`

Django is using the `admin_list_filter` template tag from Django's `admin_list` instead of Grapelli`s `grp_tags`.

Looks like changing the order in the load tag fix the issue:
`{% load i18n admin_urls static admin_list grp_tags %}`

**Comment by sehmaschine** [comment]
@pricco I'm sorry, but I don't understand what the issue is exactly. What's the unwanted behaviour and how am I able to reproduce it?

**Comment by sutris** [comment]
Hi @sehmaschine,

`change_list_filter_confirm` currently loads `grp_tags` before `admin_list`, which result in the template to use `admin_list_filter` method of `admin_list` instead of `grp_tags`. As a result, the rendered filters always have empty `data-field-name` attribute causing the following [claim](https://django-grappelli.readthedocs.io/en/latest/customization.html#filters-as-drop-down-manually-applied) to be not true:
> This template supports use cases where multiple filters have to be selected and applied at the same time.

**Comment by sehmaschine** [comment]
solved with 7eeb284
