### ISSUE TITLE
Wrong utf-8 characters in tiny_mce static files

### ISSUE THREAD

**Issue by ricard33** [sehmaschine/django-grappelli#988]
After upgrading django-grappelli to version 3.0.1, the command `python manage.py collectstatic` fails to decode two files from tiny_mce : 
* grappelli/tinymce/jscripts/tiny_mce/plugins/spellchecker/editor_plugin.js
* grappelli/tinymce/jscripts/tiny_mce/plugins/spellchecker/editor_plugin_src.js

Error is:
```
[...]
  File "/Users/ricard/.env/loc/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 427, in post_process
    yield from super().post_process(*args, **kwargs)
  File "/Users/ricard/.env/loc/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 247, in post_process
    for name, hashed_name, processed, _ in self._post_process(paths, adjustable_paths, hashed_files):
  File "/Users/ricard/.env/loc/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 307, in _post_process
    content = original_file.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 4560: invalid start byte
```

Opening `editor_plugin.js`and `editor_plugin_src.js`, one can see some invalid characters (respective positions are 2819 and 4560).

**Comment by Kiougar** [comment]
I have the same issue after upgrading to Django 4 and that's because the [`HashedFilesMixin`](https://github.com/django/django/blob/stable/4.0.x/django/contrib/staticfiles/storage.py#L62) now reads the contents of `*.js` files so that it can [replace the paths of JavaScript source maps](https://docs.djangoproject.com/en/4.0/releases/4.0/#django-contrib-staticfiles).

As a temporary workaround, I added my own `editor_plugin.js` and `editor_plugin_src.js` static files that are copies of the original with the invalid characters removed.

@sehmaschine I noticed you initially removed `tinymce` but then you added it back in. Any reason why we cannot remove it?

**Comment by sehmaschine** [comment]
A PR is appreciated

**Comment by Kiougar** [comment]
PR ready - @sehmaschine can you please check when you get a chance?
